# Generated by Django 4.2.6 on 2023-10-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_content', '0002_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloghomecontent',
            options={'verbose_name': 'Blog Home Content', 'verbose_name_plural': 'Blog Home Content'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
